Добавлено решение для шифров Цезаря и Виженера.
annparkhomenk/cs102 pull request #3
Opened 2021-10-19 17:23 UTC by annparkhomenk

Реализованы функции encrypt_caesar и decrypt_caesar, encrypt_vigenere и decrypt_vigenere, а также вспомогательная функция key_word для генерации ключа в шифре Виженера.

2021-10-29 16:32 UTC, anastasiiaCher requested changes
В целом с логикой и реализацией все ок, но есть ряд замечаний. Плюс Actions должны проходить

2021-10-29 16:32 UTC, anastasiiaCher commented on caesar.py
> +            o = ord(i)
Что такое `o`?

2021-10-29 16:32 UTC, anastasiiaCher commented on caesar.py
> +            if (97 <= o <= 122 - shift) or (65 <= o <= 90 - shift):
Хардкодить - плохо? Что такое 97 и 122? В данном случае `or` не обязывает нас брать выражения в скобки

2021-10-29 16:32 UTC, anastasiiaCher commented on caesar.py
> +    return plaintext
То же самое, что и по предыдущей функции.

2021-10-29 16:32 UTC, anastasiiaCher commented on rsa.py
> +    return prime
Под логическое значение можно не вводить переменную, а сразу возвращать через `return`

2021-10-29 16:32 UTC, anastasiiaCher commented on vigenere.py
> +def key_word(text, keyword):
Реализация шифра виженера не предполагает введения вспомогательных функций. Можно сделать проще

2021-10-29 16:32 UTC, anastasiiaCher commented on vigenere.py
> +    for i in range(len(plaintext)):
Здесь лучше сделать так: `for i, letter in enumerate(plaintext)`, чтобы дальше не обращаться по индексу к строке

2021-10-29 16:32 UTC, anastasiiaCher commented on vigenere.py
> +    for i in range(len(plaintext)):
Дальше по коду замечания те же, что и по цезарю

2021-11-01 11:49 UTC, annparkhomenk commented
Я исправила ошибки, про которые Вы написали. Насчет Actions не знаю, там в mypy пишут, что в rsa name '..' not defined, хотя все переменные определены.

2021-11-04 10:27 UTC, annparkhomenk commented
Оказалось, что изначально я загрузила файлы не туда (не в папку homework01, а просто на ветку). Поэтому не проходили Actions. Последние коммиты -- это перенос файлов туда, куда надо, удаление ненужных файлов и исправление оформления (чтобы black проходил). Теперь Actions прошли.

2021-11-09 08:26 UTC, anastasiiaCher approved these changes
Теперь в целом все ок. Только не удаляйте больше доктесты (это то, что в тройных кавычках сразу после заголовка функции) нигде.

2021-11-09 14:50 UTC, merged