Добавлено решение для решателя Судоку.
annparkhomenk/cs102 pull request #4
Opened 2021-11-17 17:26 UTC by annparkhomenk

Реализованы функции solve(), check_solution() и generate_sudoku() вместе с вспомогательными функциями.

2021-12-30 16:25 UTC, anastasiiaCher requested changes
В целом очень хорошо

2021-12-30 16:25 UTC, anastasiiaCher commented on homework02/sudoku.py
> +            values.append(grid[i][j])
давайте заменим на списковое включение

2022-01-03 15:40 UTC, annparkhomenk commented on homework02/sudoku.py
> +            values.append(grid[i][j])
Почему-то я заменяю это на списковое включение, и у меня ломаются юниттесты (они оба раза шли 6 часов и в итоге отменились)

2022-01-05 13:23 UTC, annparkhomenk commented on homework02/sudoku.py
> +            values.append(grid[i][j])
Исправила, теперь все работает

2022-01-17 06:18 UTC, anastasiiaCher approved these changes

2022-01-19 03:56 UTC, merged